// Generated by CoffeeScript 1.3.3
(function() {
  var main;

  main = function(require) {
    var bs, jq, standart;
    if (typeof window !== "undefined") {
      jq = require('jquery');
      standart = require('sn');
      bs = require('bootstrap');
      return $(function() {
        return $('#sn').sn();
      });
    }
  };

}).call(this);
