// Generated by CoffeeScript 1.3.3

$(function() {
  var methods;
  methods = {
    init: function(options) {
      return $(this).snConf(main);
    },
    main: function(options) {
      var sn;
      sn = $(this).data(sn);
      return $.ajax({
        url: 'sn-project/settings/main.json',
        async: false,
        dataType: 'json',
        success: function(s) {
          $.extend(true, sn, s);
          return $(this).data('sn', sn);
        }
      });
    }
  };
  return $.fn.snConf = function(sn) {
    if (!sn) {
      sn = {};
    }
    if (methods[sn]) {
      return methods[sn].apply(this, Array.prototype.slice.call(arguments, 1));
    } else {
      if (typeof sn === 'object' || !sn) {
        return methods.init.apply(this, arguments);
      } else {
        return $.error('Метод ' + sn + ' не существует');
      }
    }
  };
});
