// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    var methods;
    methods = {
      init: function(options) {
        return this.each(function() {
          var def, href, sn;
          def = {
            href: 'none'
          };
          $.extend(true, def, options);
          sn = $(this).data('sn');
          href = def.href;
          switch (href.replace("/(.*)#(.*)/", "$2")) {
            case "autoload":
              break;
            case "signin":
              $("#signin-error").hide();
              return $(this).snAjax('sendRequest', {
                action: 'signin',
                debug: false
              });
            case "afterSignin":
              if (sn.result) {
                if (sn.result.response) {
                  if (sn.result.claims) {
                    $('#claims').html(sn.result.claims);
                    $(this).snTriggers('table');
                  }
                  if (sn.result.pagination) {
                    $("#pagination").html(sn.result.pagination);
                    $(this).snTriggers(pagination);
                  }
                  return $("#signin").empty();
                } else {
                  $("#inputLogin").val('');
                  $("#inputPassword").val('');
                  return $("#signin-error").show();
                }
              }
              break;
            case "submit":
              return $(this).snAjax('sendRequest', {
                action: 'submit',
                debug: false
              });
            case "afterSubmit":
              if (sn.result) {
                if (sn.result.table) {
                  $("#table").html(sn.result.table);
                  $(this).snTriggers('sort');
                  $(this).snTriggers('detail');
                  return $(this).snPlayer('onClickPlay');
                }
              }
              break;
            case "close":
              return $(this).hide();
          }
        });
      }
    };
    return $.fn.snEvents = function(sn) {
      if (!sn) {
        sn = {};
      }
      if (methods[sn]) {
        return methods[sn].apply(this, Array.prototype.slice.call(arguments, 1));
      } else {
        if (typeof sn === 'object' || !sn) {
          return methods.init.apply(this, arguments);
        } else {
          return $.error('Метод ' + sn + ' не существует');
        }
      }
    };
  });

}).call(this);
